### ISSUE TITLE
question about Body Physics Loss

### ISSUE THREAD

**Issue by GavinBupt** [zhangy76/KNOWN#3]
Dear authors, I really appreciate your KNOWN work. I have seen many HMR models, and almost all of them have the problem of the penetration. I am very happy to see that you have solved the penetration  problem in SMPL with Body Physics. I am very curious about how you implemented this part. I think that mesh collision detection is very time-consuming. Will this affect your training time? Could you share this part of the code?

**Comment by zhangy76** [comment]
Thanks for your interests! For the implementation, you may find https://github.com/vchoutas/torch-mesh-isect be very helpful, which is optimized for GPU processing. Based on my experience, the algorithm does not affect the training time much and is time friendly.

**Comment by zhangy76** [comment]
Close due to being inactive, please feel free to reopen.
